### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by likeazir** [likeazir/owo#15]
uh, there is none. that should be fixed.

**Comment by nithinkodadhavadee** [comment]
what exactly is going on here in this repo? I'm kind of curious. Is there anything that I can help you with? I'd be more than interested in doing that

**Comment by likeazir** [comment]
It's just a private discord bot as a fun sideproject and testbed for python things I want to try. I don't know what it's going to be or what it's going to end up as.
Also, it's really not that great. The main reason it is on github is that if someone wants Feature X, I can just tell them to open a pull request. However, feel free to do whatever you want with the repo. 
Should probably include that in the Readme, however, i did not expect anyone to stumble upon this and actually be interested :)
